CLASS LHC_PRPLANNING DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR PRPlanning
        RESULT result,
      createPlanningData FOR MODIFY
            IMPORTING keys FOR ACTION PRPlanning~createPlanningData RESULT result.
ENDCLASS.

CLASS LHC_PRPLANNING IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD createPlanningData.
  ENDMETHOD.

ENDCLASS.
